- name: install openstack
  hosts: guests
 
  vars_prompt:
   - name: branch
     prompt: "Introduzca la version de devstack"
     default: "kilo" 
     private: no
   - name: user
     prompt: "Introduzca el usuario"
     default: "ubuntu" 
     private: no
   - name: password
     prompt: "Introduzca la password"
     default: "password" 
     private: no
  roles:
    - openstack-guest
